// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwNro-1heLtOugl1agW17OkgoTu5hJfK8',
    appId: '1:795468580595:web:d880b0c7bfe414618c5986',
    messagingSenderId: '795468580595',
    projectId: 'the-sprinklr-bakery',
    authDomain: 'the-sprinklr-bakery.firebaseapp.com',
    storageBucket: 'the-sprinklr-bakery.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDWmgwSl5IslC0ipH4CIsz3A4_YrDxFDM',
    appId: '1:795468580595:android:4b620268f9ad863a8c5986',
    messagingSenderId: '795468580595',
    projectId: 'the-sprinklr-bakery',
    storageBucket: 'the-sprinklr-bakery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVeBtiCSQK0uWfgOjmKtH2eQE2RgPnePc',
    appId: '1:795468580595:ios:f500a5c72c8422d38c5986',
    messagingSenderId: '795468580595',
    projectId: 'the-sprinklr-bakery',
    storageBucket: 'the-sprinklr-bakery.appspot.com',
    iosBundleId: 'com.example.theSprinklrBakery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVeBtiCSQK0uWfgOjmKtH2eQE2RgPnePc',
    appId: '1:795468580595:ios:f500a5c72c8422d38c5986',
    messagingSenderId: '795468580595',
    projectId: 'the-sprinklr-bakery',
    storageBucket: 'the-sprinklr-bakery.appspot.com',
    iosBundleId: 'com.example.theSprinklrBakery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwNro-1heLtOugl1agW17OkgoTu5hJfK8',
    appId: '1:795468580595:web:3a16ff38e71cf1c38c5986',
    messagingSenderId: '795468580595',
    projectId: 'the-sprinklr-bakery',
    authDomain: 'the-sprinklr-bakery.firebaseapp.com',
    storageBucket: 'the-sprinklr-bakery.appspot.com',
  );
}
